---
- hosts: all
  name: Configure cups on raspberry
  become: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: update repositories
      ansible.builtin.apt:
        cache_valid_time: 86400
        update_cache: true
    - name: install cups
      apt: name={{ item }} state=present
      with_items: [cups, printer-driver-gutenprint]
    - name: add {{ username }} to lpadmin group
      ansible.builtin.user:
        user: '{{ username }}'
        groups: lpadmin
        append: true
    - name: configure cupsd
      ansible.builtin.copy:
        src: files/cupsd.conf
        dest: /etc/cups/cupsd.conf
        owner: root
        group: lp
        mode: '0640'
      register: service_cups
    - name: restart cups
      ansible.builtin.systemd:
        name: cups
        enabled: true
        state: restarted
      when: service_cups.changed
    - name: Ensure the directory printc exists
      ansible.builtin.file:
        path: "/home/{{ username }}/printc"
        state: directory
        mode: '0777' # Optional: Set permissions
    - name: Ensure the directory print exists
      ansible.builtin.file:
        path: "/home/{{ username }}/print"
        state: directory
        mode: '0777' # Optional: Set permissions
    - name: copy print script
      ansible.builtin.copy:
        src: files/print.sh
        dest: /opt/print.sh
        owner: root
        group: lp
        mode: '0777'
    - name: start the cron check for print.sh
      ansible.builtin.cron:
        name: "cron print pdf"
        minute: "*"
        hour: "*"
        job: "/opt/print.sh"
    - name: copy printc script
      ansible.builtin.copy:
        src: files/printc.sh
        dest: /opt/printc.sh
        owner: root
        group: lp
        mode: '0777'
    - name: start the cron check for printc.sh
      ansible.builtin.cron:
        name: "cron print pdf color"
        minute: "*"
        hour: "*"
        job: "/opt/printc.sh"
